### ISSUE TITLE
Create python program that generates a schedule without considering any rules, preferences, or other criteria as a starting point

### ISSUE THREAD

**Issue by JakeWilliams22** [JakeWilliams22/nfl-schedule-maker#4]

**Comment by coletaylor788** [comment]
Basic functionality of creating a random schedule is complete on the schedule_generator branch in the nfl-schedule-algorithm repo.

Waiting on decision of communication protocol to allow the app to communicate the schedule to the front-end.

**Comment by coletaylor788** [comment]
Edited the code to be Python 3 and added support to output to JSON. Waiting feedback on the pull request on the nfl-schedule-algorithm repo

**Comment by coletaylor788** [comment]
Need to merge and provide dummy JSON. Also need to add a new url to app.py using my new function. ("/generate-schedule")

**Comment by coletaylor788** [comment]
I left a sample JSON schedule in the nfl-schedule-algorithm repo. Also, the schedule can now be generated by hitting the python back-end server with '/generate-schedule'
