### ISSUE TITLE
Decide on a Data Transfer Type (ie JSON/XML) and Format for backend/frontend to communicate with

### ISSUE THREAD

**Issue by JakeWilliams22** [JakeWilliams22/nfl-schedule-maker#7]

**Comment by coletaylor788** [comment]
I would lean towards using JSON as it seems more modern. However, any thoughts on which is easier to work with in JS and Python? I haven't used either format with either language.

**Comment by elizabethcooper** [comment]
I've used json with Python and it's super easy

**Comment by coletaylor788** [comment]
Okay, unless there are any differing opinions, we should go with JSON.
